[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.1"
game = { path = "../game" }
space_editor = {git = "https://github.com/rewin123/space_editor.git", branch = "0.15-dev"}

[features]
devtools = []